language: java
env:
  global:
    secure: LRMnbCbjYEy5ZPLkJO7CdputVrXKLd4NGIHvo1qgIBqFePFXcxkxchW1yZGjd74j5qCmtx2TJ8Clb1t1q6NLTWrnOJoj4aVa1aPL+z7Dez8NjF31LdcFKwUjLLBAU3ca+kDAXptZH8vlDfydFr/14xgccgc+Yk4hsbMehPd3MdIK3Wsv+Frwvu5x101h9sqmmJnwDTdpixwNlEN6K8YmX+At6MQOip/q5e8PhCWk/Xkjkw/UoKQHAucNyp7ajBBYdpYVGyau/1hOLejPlQwZzrlsIBX/ZddCpiLLdrKn5pmOUHJ4BMoScveqbjoK/FvLGL3FvZby6TeVjg6W6FyzAiM9CL4XKXPNQ2anIm17AsFRrhQxw0j9pSZsKRegwzdsvLiEb25ItZXGzZP+khtFEaBfXlXI0UMfyh4f+3UYo23oTN1vS0xaBS9CfT2DXhb+j2XoQ/0lvQQdZt0OGXewWj9JApMxRN3vIpN/2DEKhMAT6H2joOsfeTFDh9GnQ/Iwx39tEkk1qiGcP4A3jIoEvX/YeDnSaqWNtQa6pCSfLRxEfnBtuXeJzOr0hqFehNVftcW1VHVJyIgBh8lRVDEhxOUW0lV30cCUURgRliIYXFRd4z0oQSUfd23sADh477MFu7+1xO8C99F1JXMyWrHE7uZg5JXXgLLcOUycDkDKkU8=
jdk:
- oraclejdk8
services:
- mongodb
- rabbitmq
sudo: required
branches:
  only:
  - staging
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- chmod a+x merge_script.sh
- BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=symbiote-h2020/InterworkingInterface
  ./merge_script.sh
- bash <(curl -s https://codecov.io/bash)
